@startuml

!includeurl https://gist.githubusercontent.com/Arnaud-Bonneuil/c317a7a30bed7d64e2b5b1f558ac00cf/raw/sober.puml

!includeurl https://raw.githubusercontent.com/SanteyneEmbeddedSystems/Embedded_Software_Metamodel/main/Physical_Elements/Metaclass_Physical_Element.puml
!includeurl https://raw.githubusercontent.com/SanteyneEmbeddedSystems/Embedded_Software_Metamodel/main/Physical_Elements/Metaclass_Classifier.puml

Physical_Element <|-- Classifier

@enduml
