@startuml

abstract class Type
{
  Abstract metaclass allowing to model an element
  used to classify a data in order to specify
  what kind of value it has and what kind of
  mathematical, relational or logical operations
  can be applied to it.
}

@enduml
