@startuml

note as Identifier_Pattern
context **Software_Element** inv:
    self.Identifier.matches("^([0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12})$")
end note

@enduml